spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.111.117:6033/fms_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://mysql.dev.harsons.cn:6033/fms_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: finauser
    password: finauser
